In [2]:
import pandas as pd

# Function to load and preprocess each file
def load_and_preprocess(file_path, skip_rows):
    df = pd.read_csv(file_path, skiprows=skip_rows, low_memory=False)
    df['Glucose'] = df['Scan Glucose mmol/L'].combine_first(df['Historic Glucose mmol/L'])
    df['Glucose'] = pd.to_numeric(df['Glucose'], errors='coerce')
    df['Timestamp'] = pd.to_datetime(df['Device Timestamp'], dayfirst=True, errors='coerce')
    df = df[['Timestamp', 'Glucose']].dropna()
    df = df.set_index('Timestamp').sort_index()
    return df[['Glucose']]

# Load and preprocess each file
df_glucose1 = load_and_preprocess('BG.csv', skip_rows=2)
df_glucose2 = load_and_preprocess('BG-1.csv', skip_rows=2)

# Concatenate the two DataFrames
df_combined = pd.concat([df_glucose1, df_glucose2])

# Handle duplicates by averaging glucose values if they share the same timestamp

# Sort the combined data by timestamp
df_combined = df_combined.sort_index()

# Save the combined data to a CSV file without specific formatting

# Display the combined and sorted data
df_combined

                     Glucose
Timestamp
2022-06-07 00:11:00     13.8
2022-06-07 00:11:00     13.8
2022-06-07 00:26:00     14.1
2022-06-07 00:26:00     14.1
2022-06-07 00:41:00     12.1
...                      ...
2024-02-20 13:16:00     12.1
2024-02-20 13:21:00     13.0
2024-02-20 13:26:00     13.7
2024-02-20 13:31:00     14.3
2024-02-20 13:36:00     14.4

[331995 rows x 1 columns]

In [3]:
duplicates = df_combined[df_combined.index.duplicated(keep=False)]
print(duplicates)

                     Glucose
Timestamp
2022-06-07 00:11:00     13.8
2022-06-07 00:11:00     13.8
2022-06-07 00:26:00     14.1
2022-06-07 00:26:00     14.1
2022-06-07 00:41:00     12.1
...                      ...
2024-02-20 04:26:00      4.0
2024-02-20 05:36:00      4.4
2024-02-20 05:36:00      4.4
2024-02-20 12:46:00      8.8
2024-02-20 12:46:00      8.9

[309680 rows x 1 columns]