In [1]:
import pandas as pd
from datetime import datetime

def read_and_process(file_path):
    df = pd.read_csv(file_path)
    df['Timestamp'] = df.apply(lambda row: datetime.utcfromtimestamp(row['startTimeInSeconds'] + row['startTimeOffsetInSeconds']).strftime('%Y-%m-%d %H:%M:%S'),axis=1)
    df = df[['Timestamp', 'activityType', 'activeKilocalories', 'steps', 'distanceInMeters', 'durationInSeconds', 
             'activeTimeInSeconds', 'startTimeInSeconds', 'startTimeOffsetInSeconds', 
             'met', 'intensity', 'meanMotionIntensity', 'maxMotionIntensity']]
    return df

file_paths = [
    '06-02-2024---06-03-2024.csv',
    '06-03-2024---04-04-2024.csv',
    '04-04-2024---30-04-2024.csv'
]

df_list = [read_and_process(file_path) for file_path in file_paths]
df_activity = pd.concat(df_list)
df_activity['Timestamp'] = pd.to_datetime(df_activity['Timestamp'])
df_activity.set_index("Timestamp", inplace=True)
df_activity.sort_index(inplace=True)
df_activity.reset_index(inplace=True)
df_activity.to_csv("Activity_Epoch.csv", index = False)
df_activity

,Timestamp,activityType,activeKilocalories,steps,distanceInMeters,durationInSeconds,activeTimeInSeconds,startTimeInSeconds,startTimeOffsetInSeconds,met,intensity,meanMotionIntensity,maxMotionIntensity
0,2024-02-06 00:00:00,SEDENTARY,0,0,0.00,900,900,1707177600,0,1.000000,SEDENTARY,0.0,3.0
1,2024-02-06 00:15:00,WALKING,0,16,11.96,900,60,1707178500,0,1.000000,ACTIVE,4.0,4.0
2,2024-02-06 00:15:00,SEDENTARY,0,0,0.00,900,840,1707178500,0,1.000000,SEDENTARY,0.0,3.0
3,2024-02-06 00:30:00,SEDENTARY,0,0,0.00,900,900,1707179400,0,1.000000,SEDENTARY,0.0,4.0
4,2024-02-06 00:45:00,SEDENTARY,0,0,0.00,900,900,1707180300,0,1.000000,SEDENTARY,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
11582,2024-04-30 00:00:00,SEDENTARY,0,0,0.00,900,900,1714431600,3600,1.000000,SEDENTARY,0.0,3.0
11583,2024-04-30 00:15:00,SEDENTARY,0,0,0.00,900,900,1714432500,3600,1.000000,SEDENTARY,0.0,4.0
11584,2024-04-30 00:30:00,SEDENTARY,0,0,0.00,900,900,1714433400,3600,1.000000,SEDENTARY,0.0,2.0
11585,2024-04-30 00:45:00,WALKING,2,22,16.45,900,120,1714434300,3600,1.733945,ACTIVE,2.0,2.0
11586,2024-04-30 00:45:00,SEDENTARY,0,0,0.00,900,780,1714434300,3600,1.000000,SEDENTARY,0.0,4.0