In [1]:
import pandas as pd
from datetime import datetime

def read_and_process(file_path):
    df = pd.read_csv(file_path)
    df['Timestamp'] = df.apply(lambda row: datetime.utcfromtimestamp(row['startTimeInSeconds'] + row['startTimeOffsetInSeconds']).strftime('%Y-%m-%d %H:%M:%S'),axis=1)
    df = df[['Timestamp', 'activityType', 'activeKilocalories', 'steps', 'distanceInMeters', 'durationInSeconds', 
             'activeTimeInSeconds', 'startTimeInSeconds', 'startTimeOffsetInSeconds', 
             'met', 'intensity', 'meanMotionIntensity', 'maxMotionIntensity']]
    return df

file_paths = [
    '18-03-2024---17-04-2024.csv',
    '17-04-2024---17-05-2024.csv',
    '17-05-2024---16-06-2024.csv'
]

df_list = [read_and_process(file_path) for file_path in file_paths]
df_activity = pd.concat(df_list)
df_activity['Timestamp'] = pd.to_datetime(df_activity['Timestamp'])
df_activity.set_index("Timestamp", inplace=True)
df_activity.sort_index(inplace=True)
df_activity.reset_index(inplace=True)
df_activity.to_csv("Activity_Epoch.csv", index = False)
df_activity

,Timestamp,activityType,activeKilocalories,steps,distanceInMeters,durationInSeconds,activeTimeInSeconds,startTimeInSeconds,startTimeOffsetInSeconds,met,intensity,meanMotionIntensity,maxMotionIntensity
0,2024-03-18 00:00:00,SEDENTARY,0,0,0.00,900,900,1710720000,0,1.0,SEDENTARY,0.0,4.0
1,2024-03-18 00:15:00,SEDENTARY,0,0,0.00,900,900,1710720900,0,1.0,SEDENTARY,0.0,0.0
2,2024-03-18 00:30:00,SEDENTARY,0,0,0.00,900,900,1710721800,0,1.0,SEDENTARY,0.0,2.0
3,2024-03-18 00:45:00,SEDENTARY,0,0,0.00,900,900,1710722700,0,1.0,SEDENTARY,0.0,3.0
4,2024-03-18 01:00:00,SEDENTARY,0,0,0.00,900,900,1710723600,0,1.0,SEDENTARY,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12041,2024-06-14 23:45:00,SEDENTARY,0,0,0.03,900,900,1718405100,3600,1.0,SEDENTARY,0.0,0.0
12042,2024-06-15 01:00:00,SEDENTARY,0,0,0.00,900,900,1718406000,7200,1.0,SEDENTARY,0.0,0.0
12043,2024-06-15 01:15:00,SEDENTARY,0,0,0.00,900,900,1718406900,7200,1.0,SEDENTARY,0.0,0.0
12044,2024-06-15 01:30:00,SEDENTARY,0,0,0.00,900,900,1718407800,7200,1.0,SEDENTARY,0.0,0.0
12045,2024-06-15 01:45:00,SEDENTARY,0,0,0.00,900,900,1718408700,7200,1.0,SEDENTARY,0.0,0.0